<?php 
# Code generated by sdkgen
# Generated on 2019-10-01 21:12:20.5838247 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\Accounts\V1\internal;

use Vendasta\Vax\HTTPClient;

class FulfillmentServiceHTTPClient extends HTTPClient implements FulfillmentServiceClientInterface
{
    /**
     * FulfillmentServiceHTTPClient constructor.
     * @param string $host
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout
     */
    public function __construct(string $host, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($host, $scope, $secure, $default_timeout);
    }
    
    /**
     * Auth wrapper for \Accounts\V1\FulfillmentServiceClient::SetAutoRenew
     * @param \Accounts\V1\SetAutoRenewRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function SetAutoRenew(\Accounts\V1\SetAutoRenewRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->doRequest(
            "/accounts.v1.FulfillmentService/SetAutoRenew",
            $req,
            "\Google\Protobuf\GPBEmpty",
            $options
        );
    }
    
}
