<?php 
# Code generated by sdkgen
# Generated on 2019-10-01 21:12:20.5838247 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\Accounts\V1\internal;

interface FulfillmentServiceClientInterface
{ 
    /**
     * Auth wrapper for \Accounts\V1\FulfillmentServiceClient::SetAutoRenew
     * @param \Accounts\V1\SetAutoRenewRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function SetAutoRenew(\Accounts\V1\SetAutoRenewRequest $req, array $options = []): \Google\Protobuf\GPBEmpty;
    
}
