<?php 
# Code generated by sdkgen
# Generated on 2019-10-01 21:12:20.5838247 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\Accounts\V1\internal;

use Vendasta\Vax\GRPCClient;

class FulfillmentServiceGRPCClient extends GRPCClient implements FulfillmentServiceClientInterface
{
    private $client;

    /**
     * Constructor for FulfillmentServiceGRPCClient
     * @param string $hostname hostname of the service to hit
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout time in milliseconds
     */
    public function __construct(string $hostname, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($hostname, $scope, $secure, $default_timeout);
        $this->client = new \Accounts\V1\FulfillmentServiceClient($hostname, $this->getClientOptions());
    }
    
    /**
     * Auth wrapper for \Accounts\V1\FulfillmentServiceClient::SetAutoRenew
     * @param \Accounts\V1\SetAutoRenewRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function SetAutoRenew(\Accounts\V1\SetAutoRenewRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->doRequest(
            array($this->client, 'SetAutoRenew'),
            $req,
            $options
        );
    }
    
}
